configure.ac: don't use bash syntax ==
otherwise build fails to detect sg3_utils like this

./configure: 18016: test: xsgutils2: unexpected operator
./configure: 18024: test: xsgutils2: unexpected operator

and fails due to missing -lsgutils2
/usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.3.0/../../../../powerpc64le-unknown-linux-gnu/bin/ld:
sysfs_SCSI_Fill.cpp:(.text+0x3080): undefined reference to
`sg_ll_inquiry'

Signed-off-by: Georgy Yakovlev <gyakovlev@gentoo.org>